name: Build Prod App

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Install @angular/cli
        run: npm i -D -E @angular/cli
      - name: Use coturiv/setup-ionic
        uses: coturiv/setup-ionic@master
        with:
          cordova-version: 8
      - run: npm ci
      - run: npm run build